
package com.itheima.crm;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICustomerService", targetNamespace = "http://cxf.itheima.com/")
@XmlSeeAlso({})
public interface ICustomerService {


    /**
     * 
     * @return
     *     returns java.util.List<com.itheima.cxf.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerNotAssociation", targetNamespace = "http://cxf.itheima.com/", className = "com.itheima.cxf.FindCustomerNotAssociation")
    @ResponseWrapper(localName = "findCustomerNotAssociationResponse", targetNamespace = "http://cxf.itheima.com/", className = "com.itheima.cxf.FindCustomerNotAssociationResponse")
    public List<Customer> findCustomerNotAssociation();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://cxf.itheima.com/", className = "com.itheima.cxf.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://cxf.itheima.com/", className = "com.itheima.cxf.SaveResponse")
    public void save(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "assignCustomersToDecidedzone", targetNamespace = "http://cxf.itheima.com/", className = "com.itheima.cxf.AssignCustomersToDecidedzone")
    @ResponseWrapper(localName = "assignCustomersToDecidedzoneResponse", targetNamespace = "http://cxf.itheima.com/", className = "com.itheima.cxf.AssignCustomersToDecidedzoneResponse")
    public void assignCustomersToDecidedzone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Integer> arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.itheima.cxf.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerHasAssociation", targetNamespace = "http://cxf.itheima.com/", className = "com.itheima.cxf.FindCustomerHasAssociation")
    @ResponseWrapper(localName = "findCustomerHasAssociationResponse", targetNamespace = "http://cxf.itheima.com/", className = "com.itheima.cxf.FindCustomerHasAssociationResponse")
    public List<Customer> findCustomerHasAssociation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.itheima.cxf.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByTelephone", targetNamespace = "http://cxf.itheima.com/", className = "com.itheima.cxf.FindByTelephone")
    @ResponseWrapper(localName = "findByTelephoneResponse", targetNamespace = "http://cxf.itheima.com/", className = "com.itheima.cxf.FindByTelephoneResponse")
    public Customer findByTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.itheima.cxf.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://cxf.itheima.com/", className = "com.itheima.cxf.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://cxf.itheima.com/", className = "com.itheima.cxf.FindAllResponse")
    public List<Customer> findAll();

}
